version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        restart: unless-stopped
        working_dir: /var/www
        ports:
            - "8000:8000"
            - "5173:5173"
        volumes:
            - .:/var/www
        depends_on:
            - mysql
        networks:
            - mini-asana

    mysql:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
        ports:
            - "${DB_TARGET_PORT:-3366}:3306"
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - mini-asana

    nginx:
        image: nginx:latest
        restart: unless-stopped
        ports:
            - "${NGINX_TARGET_PORT:-80}:80"
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - mini-asana

networks:
    mini-asana:
        driver: bridge

volumes:
    mysql_data:
        driver: local

